name: Build

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  firmware:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Install ARM toolchain
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: gcc-arm-none-eabi binutils-arm-none-eabi libnewlib-arm-none-eabi make
          version: 1.0

      - name: Build firmware
        run: make firmware
